-- MySQL Script generated by MySQL Workbench
-- Fri May 29 23:17:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital_medicine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_medicine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_medicine` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `hospital_medicine` ;

-- -----------------------------------------------------
-- Table `hospital_medicine`.`benh_nhan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`benh_nhan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ma_benh_nhan` VARCHAR(20) NOT NULL,
  `ho_ten` VARCHAR(100) NOT NULL,
  `ngay_sinh` DATE NULL DEFAULT NULL,
  `gioi_tinh` ENUM('Nam', 'Nu') NULL DEFAULT 'Nam',
  `so_dinh_danh` VARCHAR(20) NULL DEFAULT NULL,
  `so_the_bhyt` VARCHAR(15) NULL DEFAULT NULL,
  `dia_chi` VARCHAR(500) NULL DEFAULT NULL,
  `dien_thoai` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ma_benh_nhan` (`ma_benh_nhan` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`kho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten_kho` VARCHAR(100) NOT NULL,
  `loai_kho` ENUM('kho_tong', 'kho_le_ngoai_tru', 'kho_le_noi_tru', 'tu_truc') NOT NULL,
  `khoa` VARCHAR(100) NULL DEFAULT NULL,
  `trang_thai_kho` ENUM('binh_thuong', 'dang_kiem_ke') NULL DEFAULT 'binh_thuong',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`thuoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`thuoc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ma_bhyt` VARCHAR(15) NOT NULL,
  `ten_thuoc` VARCHAR(300) NOT NULL,
  `hoat_chat` VARCHAR(500) NULL DEFAULT NULL,
  `ham_luong` VARCHAR(100) NULL DEFAULT NULL,
  `don_vi_tinh` VARCHAR(50) NOT NULL,
  `duong_dung` VARCHAR(100) NULL DEFAULT NULL,
  `don_gia_thau` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `ty_le_thanh_toan` INT NULL DEFAULT '100' COMMENT 'Tỷ lệ thanh toán BHYT (%)',
  `so_dang_ky` VARCHAR(50) NULL DEFAULT NULL,
  `nuoc_san_xuat` VARCHAR(100) NULL DEFAULT NULL,
  `hang_san_xuat` VARCHAR(200) NULL DEFAULT NULL,
  `nhom_thuoc` VARCHAR(100) NULL DEFAULT NULL,
  `dinh_muc_toi_thieu` INT NULL DEFAULT '10',
  `trang_thai` TINYINT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ma_bhyt` (`ma_bhyt` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`nguoi_dung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`nguoi_dung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten_dang_nhap` VARCHAR(50) NOT NULL,
  `mat_khau` VARCHAR(255) NOT NULL,
  `ho_ten` VARCHAR(100) NOT NULL,
  `vai_tro` ENUM('duoc_si_tong', 'duoc_si_kho_le', 'dieu_duong', 'ke_toan', 'bac_si') NOT NULL,
  `kho_id` INT NULL DEFAULT NULL,
  `trang_thai` TINYINT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ten_dang_nhap` (`ten_dang_nhap` ASC) VISIBLE,
  INDEX `kho_id` (`kho_id` ASC) VISIBLE,
  CONSTRAINT `nguoi_dung_ibfk_1`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`bien_dong_kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`bien_dong_kho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kho_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `loai_bien_dong` ENUM('nhap', 'xuat_cap_phat', 'xuat_dieu_chuyen', 'nhap_dieu_chuyen', 'xuat_tu_truc', 'hoan_ung', 'kiem_ke_tang', 'kiem_ke_giam') NOT NULL,
  `so_luong` INT NOT NULL,
  `so_luong_truoc` INT NULL DEFAULT '0',
  `so_luong_sau` INT NULL DEFAULT '0',
  `phieu_lien_quan` VARCHAR(50) NULL DEFAULT NULL,
  `nguoi_thuc_hien_id` INT NULL DEFAULT NULL,
  `ngay_bien_dong` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  INDEX `nguoi_thuc_hien_id` (`nguoi_thuc_hien_id` ASC) VISIBLE,
  INDEX `idx_bien_dong_ngay` (`ngay_bien_dong` ASC) VISIBLE,
  INDEX `idx_bien_dong_kho` (`kho_id` ASC, `thuoc_id` ASC) VISIBLE,
  CONSTRAINT `bien_dong_kho_ibfk_1`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `bien_dong_kho_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`),
  CONSTRAINT `bien_dong_kho_ibfk_3`
    FOREIGN KEY (`nguoi_thuc_hien_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`danh_muc_icd10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`danh_muc_icd10` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ma_benh` VARCHAR(10) NOT NULL,
  `ten_benh` VARCHAR(500) NOT NULL,
  `thuoc_phu_luc_2` TINYINT NULL DEFAULT '0',
  `ghi_chu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ma_benh` (`ma_benh` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`dot_dieu_tri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`dot_dieu_tri` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `benh_nhan_id` INT NOT NULL,
  `loai_hinh` ENUM('ngoai_tru', 'noi_tru') NOT NULL,
  `khoa` VARCHAR(100) NULL DEFAULT NULL,
  `ngay_vao` DATETIME NOT NULL,
  `ngay_ra` DATETIME NULL DEFAULT NULL,
  `ma_benh` VARCHAR(10) NULL DEFAULT NULL,
  `chan_doan_lam_sang` VARCHAR(500) NULL DEFAULT NULL,
  `muc_huong` INT NULL DEFAULT '80' COMMENT '80, 95, hoặc 100',
  `trang_thai` ENUM('dang_dieu_tri', 'da_chot_vien_phi', 'da_xuat_xml') NULL DEFAULT 'dang_dieu_tri',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `benh_nhan_id` (`benh_nhan_id` ASC) VISIBLE,
  INDEX `ma_benh` (`ma_benh` ASC) VISIBLE,
  CONSTRAINT `dot_dieu_tri_ibfk_1`
    FOREIGN KEY (`benh_nhan_id`)
    REFERENCES `hospital_medicine`.`benh_nhan` (`id`),
  CONSTRAINT `dot_dieu_tri_ibfk_2`
    FOREIGN KEY (`ma_benh`)
    REFERENCES `hospital_medicine`.`danh_muc_icd10` (`ma_benh`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_phi_bhyt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_phi_bhyt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dot_dieu_tri_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `so_luong` INT NOT NULL,
  `don_gia` DECIMAL(15,2) NOT NULL,
  `ty_le_tt` INT NULL DEFAULT '100',
  `muc_huong` INT NULL DEFAULT '80',
  `tien_bhyt` DECIMAL(15,2) NULL DEFAULT '0.00',
  `tien_bn_cung_tra` DECIMAL(15,2) NULL DEFAULT '0.00',
  `tien_bn_tu_tuc` DECIMAL(15,2) NULL DEFAULT '0.00',
  `nguon` ENUM('ngoai_tru', 'noi_tru', 'tu_truc') NOT NULL,
  `ngay_ghi_nhan` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `dot_dieu_tri_id` (`dot_dieu_tri_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_phi_bhyt_ibfk_1`
    FOREIGN KEY (`dot_dieu_tri_id`)
    REFERENCES `hospital_medicine`.`dot_dieu_tri` (`id`),
  CONSTRAINT `chi_phi_bhyt_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`don_thuoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`don_thuoc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dot_dieu_tri_id` INT NOT NULL,
  `bac_si_ke` VARCHAR(100) NULL DEFAULT NULL,
  `ngay_ke` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `chan_doan` VARCHAR(500) NULL DEFAULT NULL,
  `trang_thai` ENUM('moi', 'da_cap_phat', 'huy') NULL DEFAULT 'moi',
  PRIMARY KEY (`id`),
  INDEX `dot_dieu_tri_id` (`dot_dieu_tri_id` ASC) VISIBLE,
  CONSTRAINT `don_thuoc_ibfk_1`
    FOREIGN KEY (`dot_dieu_tri_id`)
    REFERENCES `hospital_medicine`.`dot_dieu_tri` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_cap_phat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_cap_phat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `don_thuoc_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `kho_xuat_id` INT NOT NULL,
  `so_luong_phat` INT NOT NULL,
  `don_gia` DECIMAL(15,2) NOT NULL,
  `tien_bhyt_chi_tra` DECIMAL(15,2) NULL DEFAULT '0.00',
  `tien_bn_dong_chi_tra` DECIMAL(15,2) NULL DEFAULT '0.00',
  `tien_bn_tu_tuc` DECIMAL(15,2) NULL DEFAULT '0.00',
  `ngay_cap_phat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nguoi_cap_phat_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `don_thuoc_id` (`don_thuoc_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  INDEX `kho_xuat_id` (`kho_xuat_id` ASC) VISIBLE,
  INDEX `nguoi_cap_phat_id` (`nguoi_cap_phat_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_cap_phat_ibfk_1`
    FOREIGN KEY (`don_thuoc_id`)
    REFERENCES `hospital_medicine`.`don_thuoc` (`id`),
  CONSTRAINT `chi_tiet_cap_phat_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`),
  CONSTRAINT `chi_tiet_cap_phat_ibfk_3`
    FOREIGN KEY (`kho_xuat_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `chi_tiet_cap_phat_ibfk_4`
    FOREIGN KEY (`nguoi_cap_phat_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`phieu_dieu_chuyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`phieu_dieu_chuyen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loai_phieu` ENUM('DIEU_CHUYEN', 'HOAN_UNG') NOT NULL,
  `kho_xuat_id` INT NOT NULL,
  `kho_nhan_id` INT NOT NULL,
  `nguoi_lap_id` INT NOT NULL,
  `nguoi_duyet_id` INT NULL DEFAULT NULL,
  `ngay_lap` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ngay_duyet` DATETIME NULL DEFAULT NULL,
  `trang_thai` ENUM('cho_duyet', 'dang_van_chuyen', 'hoan_thanh', 'tu_choi') NULL DEFAULT 'cho_duyet',
  `ghi_chu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `kho_xuat_id` (`kho_xuat_id` ASC) VISIBLE,
  INDEX `kho_nhan_id` (`kho_nhan_id` ASC) VISIBLE,
  INDEX `nguoi_lap_id` (`nguoi_lap_id` ASC) VISIBLE,
  INDEX `nguoi_duyet_id` (`nguoi_duyet_id` ASC) VISIBLE,
  CONSTRAINT `phieu_dieu_chuyen_ibfk_1`
    FOREIGN KEY (`kho_xuat_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `phieu_dieu_chuyen_ibfk_2`
    FOREIGN KEY (`kho_nhan_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `phieu_dieu_chuyen_ibfk_3`
    FOREIGN KEY (`nguoi_lap_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`),
  CONSTRAINT `phieu_dieu_chuyen_ibfk_4`
    FOREIGN KEY (`nguoi_duyet_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_dieu_chuyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_dieu_chuyen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phieu_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `so_lo` VARCHAR(50) NULL DEFAULT NULL,
  `han_dung` DATE NULL DEFAULT NULL,
  `so_luong_yeu_cau` INT NOT NULL,
  `so_luong_thuc_xuat` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `phieu_id` (`phieu_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_dieu_chuyen_ibfk_1`
    FOREIGN KEY (`phieu_id`)
    REFERENCES `hospital_medicine`.`phieu_dieu_chuyen` (`id`),
  CONSTRAINT `chi_tiet_dieu_chuyen_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_don_thuoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_don_thuoc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `don_thuoc_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `so_luong` INT NOT NULL,
  `lieu_dung` VARCHAR(200) NULL DEFAULT NULL,
  `ghi_chu` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `don_thuoc_id` (`don_thuoc_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_don_thuoc_ibfk_1`
    FOREIGN KEY (`don_thuoc_id`)
    REFERENCES `hospital_medicine`.`don_thuoc` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `chi_tiet_don_thuoc_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`kiem_ke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`kiem_ke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kho_id` INT NOT NULL,
  `nguoi_kiem_ke_id` INT NOT NULL,
  `ngay_bat_dau` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ngay_ket_thuc` DATETIME NULL DEFAULT NULL,
  `trang_thai` ENUM('dang_thuc_hien', 'hoan_thanh') NULL DEFAULT 'dang_thuc_hien',
  PRIMARY KEY (`id`),
  INDEX `kho_id` (`kho_id` ASC) VISIBLE,
  INDEX `nguoi_kiem_ke_id` (`nguoi_kiem_ke_id` ASC) VISIBLE,
  CONSTRAINT `kiem_ke_ibfk_1`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `kiem_ke_ibfk_2`
    FOREIGN KEY (`nguoi_kiem_ke_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_kiem_ke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_kiem_ke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kiem_ke_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `so_lo` VARCHAR(50) NULL DEFAULT NULL,
  `so_luong_he_thong` INT NOT NULL,
  `so_luong_thuc_te` INT NULL DEFAULT NULL,
  `chenh_lech` INT GENERATED ALWAYS AS ((coalesce(`so_luong_thuc_te`,0) - `so_luong_he_thong`)) STORED,
  `ghi_chu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `kiem_ke_id` (`kiem_ke_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_kiem_ke_ibfk_1`
    FOREIGN KEY (`kiem_ke_id`)
    REFERENCES `hospital_medicine`.`kiem_ke` (`id`),
  CONSTRAINT `chi_tiet_kiem_ke_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`nha_cung_cap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`nha_cung_cap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten_nha_cung_cap` VARCHAR(200) NOT NULL,
  `dia_chi` VARCHAR(500) NULL DEFAULT NULL,
  `ma_so_thue` VARCHAR(20) NULL DEFAULT NULL,
  `dien_thoai` VARCHAR(20) NULL DEFAULT NULL,
  `trang_thai` TINYINT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`phieu_nhap_kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`phieu_nhap_kho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `so_hoa_don` VARCHAR(50) NOT NULL,
  `nha_cung_cap_id` INT NOT NULL,
  `kho_id` INT NOT NULL,
  `nguoi_lap_id` INT NOT NULL,
  `ngay_lap` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tong_tien` DECIMAL(18,2) NULL DEFAULT '0.00',
  `ghi_chu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `nha_cung_cap_id` (`nha_cung_cap_id` ASC) VISIBLE,
  INDEX `kho_id` (`kho_id` ASC) VISIBLE,
  INDEX `nguoi_lap_id` (`nguoi_lap_id` ASC) VISIBLE,
  CONSTRAINT `phieu_nhap_kho_ibfk_1`
    FOREIGN KEY (`nha_cung_cap_id`)
    REFERENCES `hospital_medicine`.`nha_cung_cap` (`id`),
  CONSTRAINT `phieu_nhap_kho_ibfk_2`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `phieu_nhap_kho_ibfk_3`
    FOREIGN KEY (`nguoi_lap_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_nhap_kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_nhap_kho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phieu_nhap_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `so_lo` VARCHAR(50) NOT NULL,
  `han_dung` DATE NOT NULL,
  `so_luong` INT NOT NULL,
  `don_gia` DECIMAL(15,2) NOT NULL,
  `thue_vat` DECIMAL(5,2) NULL DEFAULT '0.00',
  `thanh_tien` DECIMAL(18,2) GENERATED ALWAYS AS (((`so_luong` * `don_gia`) * (1 + (`thue_vat` / 100)))) STORED,
  PRIMARY KEY (`id`),
  INDEX `phieu_nhap_id` (`phieu_nhap_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_nhap_kho_ibfk_1`
    FOREIGN KEY (`phieu_nhap_id`)
    REFERENCES `hospital_medicine`.`phieu_nhap_kho` (`id`),
  CONSTRAINT `chi_tiet_nhap_kho_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`phieu_hoan_ung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`phieu_hoan_ung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kho_tu_truc_id` INT NOT NULL,
  `khoa_yeu_cau` VARCHAR(100) NOT NULL,
  `nguoi_lap_id` INT NOT NULL,
  `nguoi_duyet_id` INT NULL DEFAULT NULL,
  `ngay_lap` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ngay_duyet` DATETIME NULL DEFAULT NULL,
  `trang_thai` ENUM('cho_duyet', 'da_hoan_thanh', 'tu_choi') NULL DEFAULT 'cho_duyet',
  PRIMARY KEY (`id`),
  INDEX `kho_tu_truc_id` (`kho_tu_truc_id` ASC) VISIBLE,
  INDEX `nguoi_lap_id` (`nguoi_lap_id` ASC) VISIBLE,
  INDEX `nguoi_duyet_id` (`nguoi_duyet_id` ASC) VISIBLE,
  CONSTRAINT `phieu_hoan_ung_ibfk_1`
    FOREIGN KEY (`kho_tu_truc_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `phieu_hoan_ung_ibfk_2`
    FOREIGN KEY (`nguoi_lap_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`),
  CONSTRAINT `phieu_hoan_ung_ibfk_3`
    FOREIGN KEY (`nguoi_duyet_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_phieu_hoan_ung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_phieu_hoan_ung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phieu_hoan_ung_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `so_luong_yeu_cau` INT NOT NULL,
  `so_luong_thuc_xuat` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `phieu_hoan_ung_id` (`phieu_hoan_ung_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_phieu_hoan_ung_ibfk_1`
    FOREIGN KEY (`phieu_hoan_ung_id`)
    REFERENCES `hospital_medicine`.`phieu_hoan_ung` (`id`),
  CONSTRAINT `chi_tiet_phieu_hoan_ung_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`phieu_linh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`phieu_linh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `khoa` VARCHAR(100) NOT NULL,
  `nguoi_lap_id` INT NOT NULL,
  `ngay_lap` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `trang_thai` ENUM('dang_cho_duyet', 'da_cap_phat', 'huy') NULL DEFAULT 'dang_cho_duyet',
  PRIMARY KEY (`id`),
  INDEX `nguoi_lap_id` (`nguoi_lap_id` ASC) VISIBLE,
  CONSTRAINT `phieu_linh_ibfk_1`
    FOREIGN KEY (`nguoi_lap_id`)
    REFERENCES `hospital_medicine`.`nguoi_dung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`chi_tiet_phieu_linh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`chi_tiet_phieu_linh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phieu_linh_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `so_luong_yeu_cau` INT NOT NULL,
  `so_luong_cap_phat` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `phieu_linh_id` (`phieu_linh_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `chi_tiet_phieu_linh_ibfk_1`
    FOREIGN KEY (`phieu_linh_id`)
    REFERENCES `hospital_medicine`.`phieu_linh` (`id`),
  CONSTRAINT `chi_tiet_phieu_linh_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`hang_cho_hoan_ung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`hang_cho_hoan_ung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kho_tu_truc_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `dot_dieu_tri_id` INT NULL DEFAULT NULL,
  `so_luong` INT NOT NULL,
  `ngay_xuat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `trang_thai` ENUM('cho_lap_phieu', 'da_lap_phieu', 'da_hoan_ung') NULL DEFAULT 'cho_lap_phieu',
  PRIMARY KEY (`id`),
  INDEX `kho_tu_truc_id` (`kho_tu_truc_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  INDEX `dot_dieu_tri_id` (`dot_dieu_tri_id` ASC) VISIBLE,
  CONSTRAINT `hang_cho_hoan_ung_ibfk_1`
    FOREIGN KEY (`kho_tu_truc_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `hang_cho_hoan_ung_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`),
  CONSTRAINT `hang_cho_hoan_ung_ibfk_3`
    FOREIGN KEY (`dot_dieu_tri_id`)
    REFERENCES `hospital_medicine`.`dot_dieu_tri` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`lo_thuoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`lo_thuoc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `thuoc_id` INT NOT NULL,
  `so_lo` VARCHAR(50) NOT NULL,
  `han_dung` DATE NOT NULL,
  `gia_nhap` DECIMAL(15,2) NOT NULL,
  `thue_vat` DECIMAL(5,2) NULL DEFAULT '0.00',
  `kho_id` INT NOT NULL,
  `so_luong_ton` INT NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_lo_kho` (`thuoc_id` ASC, `so_lo` ASC, `kho_id` ASC) VISIBLE,
  INDEX `idx_lo_han_dung` (`han_dung` ASC) VISIBLE,
  INDEX `idx_lo_kho` (`kho_id` ASC, `thuoc_id` ASC) VISIBLE,
  CONSTRAINT `lo_thuoc_ibfk_1`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`),
  CONSTRAINT `lo_thuoc_ibfk_2`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`y_lenh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`y_lenh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dot_dieu_tri_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `so_luong` INT NOT NULL,
  `lieu_dung` VARCHAR(200) NULL DEFAULT NULL,
  `ngay_y_lenh` DATE NOT NULL,
  `buoi` ENUM('sang', 'chieu', 'toi') NULL DEFAULT 'sang',
  `bac_si_chi_dinh` VARCHAR(100) NULL DEFAULT NULL,
  `trang_thai` ENUM('chua_linh', 'dang_cho_duyet', 'da_linh') NULL DEFAULT 'chua_linh',
  PRIMARY KEY (`id`),
  INDEX `dot_dieu_tri_id` (`dot_dieu_tri_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `y_lenh_ibfk_1`
    FOREIGN KEY (`dot_dieu_tri_id`)
    REFERENCES `hospital_medicine`.`dot_dieu_tri` (`id`),
  CONSTRAINT `y_lenh_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`phieu_linh_y_lenh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`phieu_linh_y_lenh` (
  `phieu_linh_id` INT NOT NULL,
  `y_lenh_id` INT NOT NULL,
  PRIMARY KEY (`phieu_linh_id`, `y_lenh_id`),
  INDEX `y_lenh_id` (`y_lenh_id` ASC) VISIBLE,
  CONSTRAINT `phieu_linh_y_lenh_ibfk_1`
    FOREIGN KEY (`phieu_linh_id`)
    REFERENCES `hospital_medicine`.`phieu_linh` (`id`),
  CONSTRAINT `phieu_linh_y_lenh_ibfk_2`
    FOREIGN KEY (`y_lenh_id`)
    REFERENCES `hospital_medicine`.`y_lenh` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_medicine`.`ton_kho_tu_truc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_medicine`.`ton_kho_tu_truc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kho_id` INT NOT NULL,
  `thuoc_id` INT NOT NULL,
  `lo_thuoc_id` INT NULL DEFAULT NULL,
  `so_lo` VARCHAR(50) NULL DEFAULT NULL,
  `han_dung` DATE NULL DEFAULT NULL,
  `so_luong_ton` INT NULL DEFAULT '0',
  `co_so_tran` INT NULL DEFAULT '50' COMMENT 'Định mức tối đa tủ trực',
  PRIMARY KEY (`id`),
  INDEX `kho_id` (`kho_id` ASC) VISIBLE,
  INDEX `thuoc_id` (`thuoc_id` ASC) VISIBLE,
  CONSTRAINT `ton_kho_tu_truc_ibfk_1`
    FOREIGN KEY (`kho_id`)
    REFERENCES `hospital_medicine`.`kho` (`id`),
  CONSTRAINT `ton_kho_tu_truc_ibfk_2`
    FOREIGN KEY (`thuoc_id`)
    REFERENCES `hospital_medicine`.`thuoc` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
